### ISSUE TITLE
.Rmd files missing from _bookdown.yml

### ISSUE THREAD

**Issue by jtr13** [jtr13/cc20#106]
@andycho97 some or all of the filenames were not added to the `_bookdown.yml` when you merged the pull requests. Can you edit the current version of the `_bookdown.yml` adding in those files in the proper place? You can do this directly on GitHub. Thanks!!

**Comment by andycho97** [comment]
@jtr13 Apologies for this! I added the Rmd files for the ones I have merged: https://github.com/jtr13/cc20/commit/e0f256396617c02d094fb303d8ca76a6e6826db0#diff-42a58381e95452b8042ac17313c61d81eefca342ccba66b50fe8af8b5bf72d98

https://github.com/jtr13/cc20/commit/83ccea2a95ad946685dd248e961d931d91f05152#diff-42a58381e95452b8042ac17313c61d81eefca342ccba66b50fe8af8b5bf72d98 (Visualization in Python was classified under Other topics)

I still have 2 more to merge, while waiting for changes from the authors.

-Andy

**Comment by jtr13** [comment]
No problem, thanks for fixing!
