### ISSUE TITLE
Consider  a separate "cheatsheet" section in the `cc20` book

### ISSUE THREAD

**Issue by cpaynerogers** [jtr13/cc20#76]
I have a pull request open that updates the current chapter labels and adds an appendix for chapter organization. The book, in that pull request, consists of nine parts: introduction, data processing, data visualization, results reporting, complete analyses, other topics, live tutorials, translations, and appendices. My changes added and reorganized the chapters a bit and although they may have been opinionated, I'd like to discuss whether it makes sense for cheat sheets to have their own section in the book. It at least makes sense that any cheat sheet that links to a PDF (maybe they all do) to have its own chapter, and for that chapter to get added right before the appendices, so the "flow" of the book isn't interrupted by PDF opening.

**Comment by cpaynerogers** [comment]
@ybliu9 , let me know what you think!

**Comment by ybliu9** [comment]
Agree with you! I will update the labels as well as the _bookdown.yml to reflect the changes.
