### ISSUE TITLE
Issue rendering 'speed-up-in-r-programming.Rmd'

### ISSUE THREAD

**Issue by lubin-liu** [jtr13/cc20#94]
The link for 'speed-up-in-r-programming.Rmd'

https://jtr13.github.io/cc20/speed-up-in-r-programming.html

would not load for me, but other pages on the bookdown is fine, I'm not sure if this is an issue on my machine or not.

**Comment by jtr13** [comment]
It's fixed now. I believe the problem was caused by an `install.packages()` statement that I have commented out. There's still an issue with that chapter writing files; I will create a new issue and tag the chapter author.
