### ISSUE TITLE
'speed-up-in-r-programming.Rmd' writes files to root directory

### ISSUE THREAD

**Issue by jtr13** [jtr13/cc20#95]
This chapter is writing the following files to the root directory:
```
n100distgaussian.txt    n200distt5.txt          n400distt1.txt
n100distt1.txt          n300distgaussian.txt    n400distt5.txt
n100distt5.txt          n300distt1.txt          n500distgaussian.txt
n200distgaussian.txt    n300distt5.txt          n500distt1.txt
n200distt1.txt          n400distgaussian.txt    n500distt5.txt
```

If they are needed they should be written to the resources file but ideally the chapter should not have any processes that write files. Please take a look and submit a new pull request to fix. @graceliudata

**Comment by graceliudata** [comment]
Hi Professor, we updated the autoSim.R file to resolve this issue. Thanks!

**Comment by jtr13** [comment]
Great, thank you!
